language: java
after_success:
- mvn deploy
before_install:
- openssl aes-256-cbc -K $encrypted_049c3bc6eae0_key -iv $encrypted_049c3bc6eae0_iv
  -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml
